### ISSUE TITLE
Cannot find module 'metalsmith-placeholder'

### ISSUE THREAD

**Issue by jczerwinski** [mattly/metalsmith-placeholder#1]
Gotta build index.js!

**Comment by mattly** [comment]
man, and here I thought npm was gonna do that for me. thanks!

**Comment by jczerwinski** [comment]
It's supposed to. Looks like you have it right. Maybe update your npm and try again? There were some versions where it didn't work right apparently

**Comment by mattly** [comment]
ok, fixed and published, grab 0.1.1.  Seems the precompile has to be done with `babel` not `babel-node`.

**Comment by jczerwinski** [comment]
Speedy. Thanks! :)
